apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: go-app-service           # The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: go-app 
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - name: http
    port: 9000
    targetPort: 8000
